PREFIX sto: <https://w3id.org/i40/sto#> 



#construct {
#	?s a sto:Concern .
#} where {
#	?s a sto:Concern .
#}


construct {
	?s <https://w3id.org/i40/sto#supports> ?o .
	# concerns not yet part of the hierarchy (no partOf relation incoming or outgoing) are ignored
} where {
	
	?s sto:supports ?o .
	#?s a sto:Concern 
	#FILTER(not exists { ?s a sto:Concern } ) .
	
} 