PREFIX sto: <https://w3id.org/i40/sto#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?obj
WHERE {
    ?std sto:hasDBpediaResource ?r . 
    ?std rdf:type sto:StandardOrganization.
    ?std ?pred ?obj .
    FILTER ( ?obj!=sto:StandardOrganization && ?obj!= owl:NamedIndividual && ?pred = rdf:type && ?obj!= owl:Thing)
} 