PREFIX sto: <https://w3id.org/i40/sto#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(?std) as ?sameAsLinks) 
WHERE {
    ?std sto:hasDBpediaResource ?r . 
    ?std rdf:type sto:Standard .
    ?std ?pred ?obj .
  FILTER (?pred = owl:sameAs)
} 