PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sto: <https://w3id.org/i40/sto#>
SELECT ?firstStandardLabelString ?secondStandardLabelString 
WHERE {
  ?firstStandard sto:relatedTo+|^sto:relatedTo ?secondStandard .
  ?firstStandard  rdfs:label ?firstStandardLabel . 
  ?secondStandard rdfs:label  ?secondStandardLabel .
  BIND (STR(?firstStandardLabel)  AS ?firstStandardLabelString) .
  BIND (STR(?secondStandardLabel)  AS ?secondStandardLabelString) .
} 
