PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sto: <https://w3id.org/i40/sto#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?sub ?pred ?obj
WHERE {
  ?sub ?pred ?obj.
  ?pred rdfs:subPropertyOf* sto:relatedTo .
  
} 