@prefix sto: <https://w3id.org/i40/sto#> .
@prefix dc:  <http://purl.org/dc/terms/> .
sto:OPC_Foundation  rdf:type  sto:SDO ;
 sto:name                 "OPC Foundation"@en;
 dc:description "Industry consortium that creates and maintains..."@en;
 sto:abbreviation         "OPC";
 sto:formationDate        "1994-01-01"^^xsd:date;
 sto:hasDBpediaResource   <http://dbpedia.org/resource/Association_...>;
 sto:hasOfficialResource  <https://opcfoundation.org/>;
 sto:hasWikidataEntity    <https://www.wikidata.org/entity/Q7072814>;
 sto:hasWikipediaArticle  <https://en.wikipedia.org/wiki/OPC_Foundation>.
